// <auto-generated />
using System;
using FieldVisits.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldVisits.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621130845_AddVisitLocation")]
    partial class AddVisitLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldVisits.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "busra@test.com",
                            Name = "Büşra",
                            Role = "Field"
                        },
                        new
                        {
                            Id = 2,
                            Email = "admin@test.com",
                            Name = "Admin",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ayse.demir@test.com",
                            Name = "Ayşe Demir",
                            Role = "Field"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mehmet.kaya@test.com",
                            Name = "Mehmet Kaya",
                            Role = "Field"
                        },
                        new
                        {
                            Id = 5,
                            Email = "fatma.sahin@test.com",
                            Name = "Fatma Şahin",
                            Role = "Field"
                        },
                        new
                        {
                            Id = 6,
                            Email = "ali.celik@test.com",
                            Name = "Ali Çelik",
                            Role = "Field"
                        });
                });

            modelBuilder.Entity("FieldVisits.API.Models.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CustomerName", "VisitDate")
                        .IsUnique()
                        .HasDatabaseName("IX_Visits_UserId_CustomerName_VisitDate");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("FieldVisits.API.Models.Entities.Visit", b =>
                {
                    b.HasOne("FieldVisits.API.Models.Entities.User", "User")
                        .WithMany("Visits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FieldVisits.API.Models.Entities.User", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
